import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import { HeaderMessage } from "@/components/layout/HeaderMessage";
import { Toaster } from "react-hot-toast";
import { Footer } from "@/components/layout/Footer";
import SearchBar from "@/components/layout/SearchBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "RAILR",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, user-scalable=no" />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col bg-white text-black`}
      >
        <Toaster />
        <HeaderMessage />
        <Header />
        <div className="flex-1 relative bg-white rounded-b-3xl z-10 shadow-xl">
          {children}
        </div>
        <SearchBar />
        <Footer />
      </body>
    </html>
  );
}
